version: '3.9'

services:
  nestapp:
    container_name: customershl
    image: customershl:1.0.0
    build: .
    ports:
      - 3001:3001
    environment:
      - DB_TYPE=postgres
      - PG_HOST=customerdb 
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
    
volumes:
  pgdata: {}
